
default_platform(:android)

platform :android do
  desc "Lane For android Firebase App Distrubution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --split-per-abi"
    firebase_app_distribution(
            app: "1:847898941499:android:10fb6be5625e215b75641e",
            firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-x86_64-production-release.apk",
            testers: "elbahnasawy114@gmail.com",
            release_notes: "first release on firebase_distribution"
        )
    end
end
