name: Android CI/CD with Fastlane and Firebase App Distribution

on:
  push:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Set up Java (JDK)
        uses: actions/setup-java@v4 
        with:
          distribution: 'temurin'
          java-version: '17' 

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Set up Ruby and Install Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.3
          bundler-cache: true
          working-directory: android


      - name: Build Android APK with Fastlane
        working-directory: android
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: bundle exec fastlane android firebase_distribution